services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai_tool_search_backend
    ports:
      - "8000:8000"
    environment:
      - USE_NUMPY=1
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENV=${PINECONE_ENV}
      - INDEX_NAME=${INDEX_NAME}
      - OLLAMA_VERIFY_SSL=${OLLAMA_VERIFY_SSL:-false}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - ENVIRONMENT=${ENVIRONMENT}
      - DEV_MODEL=${DEV_MODEL}
      - PROD_MODEL=${PROD_MODEL}
      - NOMIC_API_KEY=${NOMIC_API_KEY}
      # Add OpenAI (only for query tools)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
    volumes:
      - ./backend:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"